#!/user/bin/python
# -*- coding:utf-8 -*-
import requests
data={"username":"18042311448",
      "password":"J2N+5h0EkRg7ytkahQtBmUTBPPu9n7agTG5ZXh74tLHpflWsGwlGHdQn0Gp+Y2/bM8EG3F9/s90x32l6643N7K1i7G4LMJE2aWze/HorrMmDiQ2s+lQtVMAQ4i6tTzAhIqUPdL1JPHTjPcQZO0PNMocPVrtY8CUYis+a8tv+6Bo=",
      "device_id":"Ap_1tfkRWS6uF1Ugd7jh64TaDeCVtxW3p5GvrwzR5ZFF"}
header={'application/x-www-form-urlencoded; charset=UTF-8'}
s=requests.Session("http://jdshop.shopjian.cn/public/index.php/api/index/login/dologin",data,headers=header)
r=s.get("http://jdshop.shopjian.cn/public/index.php/api/card/card/status")
r.text


